CXX = g++
CPPFLAGS = -g -std=c++11 -Wall
B_DIR = bin

all: search coloring

search: search.cpp
	$(CXX) $(CPPFLAGS) search.cpp -o search
	
coloring: coloring.cpp
	$(CXX) $(CPPFLAGS) coloring.cpp -o coloring
